"""
report.py — Generates a clean Markdown skills summary report
from an AnalysisReport and saves it to disk.
"""

import os
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from config import config
from analyzer import AnalysisReport, RankedSkill

logger = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _bar(percentage: float, width: int = 30) -> str:
    """Return an ASCII progress bar string."""
    filled = round(percentage / 100 * width)
    return "█" * filled + "░" * (width - filled)


def _skill_table(skills: list[RankedSkill], total: int) -> str:
    if not skills:
        return "_No data available._\n"
    lines = [
        "| Skill | Mentions | % of listings | Frequency |",
        "|-------|----------|---------------|-----------|",
    ]
    for s in skills:
        lines.append(
            f"| `{s.name}` | {s.count} | {s.percentage}% | {_bar(s.percentage, 20)} |"
        )
    return "\n".join(lines)


def _co_occ_table(pairs: list[tuple[str, str, int]]) -> str:
    if not pairs:
        return "_No co-occurrence data._\n"
    lines = [
        "| Skill A | Skill B | Co-occurrences |",
        "|---------|---------|----------------|",
    ]
    for a, b, c in pairs:
        lines.append(f"| `{a}` | `{b}` | {c} |")
    return "\n".join(lines)


# ── Main report builder ───────────────────────────────────────────────────────

def build_markdown(report: AnalysisReport) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = report.total_listings_analysed

    md = f"""# Skills Demand Report
**Job Title:** {report.job_title}
**Industry:** {report.industry}
**Listings Analysed:** {total}
**Generated:** {ts}

---

## 1. Hard Skills (Technical)

{_skill_table(report.top_hard_skills, total)}

---

## 2. Tools, Platforms & Frameworks

{_skill_table(report.top_tools, total)}

---

## 3. Soft Skills

{_skill_table(report.top_soft_skills, total)}

---

## 4. Certifications & Qualifications

{_skill_table(report.top_certifications, total)}

---

## 5. Experience Requirements

| Range | Listings |
|-------|---------|
"""
    for exp, count in report.common_experience_ranges:
        md += f"| {exp} | {count} |\n"

    md += "\n---\n\n## 6. Education Requirements\n\n"
    md += "| Requirement | Listings |\n|------------|----------|\n"
    for edu, count in report.common_education:
        md += f"| {edu} | {count} |\n"

    md += f"""
---

## 7. Skill Co-occurrence (What Skills Appear Together)

{_co_occ_table(report.skill_co_occurrences)}

---

## 8. Top Hiring Companies

| Company | Listings |
|---------|---------|
"""
    for company, count in report.top_hiring_companies:
        md += f"| {company} | {count} |\n"

    md += "\n---\n\n_Report generated by Job Skills Scraper — SerpAPI + Claude pipeline._\n"
    return md


def save_report(report: AnalysisReport) -> tuple[str, str]:
    """
    Write the report as both Markdown and JSON to config.output_dir.
    Returns (md_path, json_path).
    """
    os.makedirs(config.output_dir, exist_ok=True)

    md_path = os.path.join(config.output_dir, config.report_filename)
    json_path = md_path.replace(".md", ".json")

    markdown = build_markdown(report)
    Path(md_path).write_text(markdown, encoding="utf-8")
    logger.info("Markdown report saved: %s", md_path)

    # Also dump raw analysis data as JSON for downstream consumption
    report_dict = {
        "job_title": report.job_title,
        "industry": report.industry,
        "total_listings_analysed": report.total_listings_analysed,
        "top_hard_skills": [
            {"name": s.name, "count": s.count, "percentage": s.percentage}
            for s in report.top_hard_skills
        ],
        "top_tools": [
            {"name": s.name, "count": s.count, "percentage": s.percentage}
            for s in report.top_tools
        ],
        "top_soft_skills": [
            {"name": s.name, "count": s.count, "percentage": s.percentage}
            for s in report.top_soft_skills
        ],
        "top_certifications": [
            {"name": s.name, "count": s.count, "percentage": s.percentage}
            for s in report.top_certifications
        ],
        "skill_co_occurrences": [
            {"skill_a": a, "skill_b": b, "count": c}
            for a, b, c in report.skill_co_occurrences
        ],
        "top_hiring_companies": [
            {"company": c, "count": n}
            for c, n in report.top_hiring_companies
        ],
    }
    Path(json_path).write_text(json.dumps(report_dict, indent=2), encoding="utf-8")
    logger.info("JSON data saved: %s", json_path)

    return md_path, json_path